---
kind: pipeline
type: docker
name: default

steps:
  - name: Build and push to private registry
    image: plugins/docker
    settings:
      username: jallier
      password:
        from_secret: docker_password
      registry: git.jallier.xyz
      repo: git.jallier.xyz/jallier/laundry-notify
      dockerfile: dockerfile
      tags:
        - latest
trigger:
  branch:
    - main
  event:
    - push
volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
